@extends('errors.layout')
@section('title', lang('Forbidden'))
@section('code', '403')
@section('message', lang('Forbidden'))
@section('description', lang('You Do not Have The Right Permission To Access.'))
