@extends('errors.layout')
@section('title', lang('Server Error'))
@section('code', '500')
@section('message', lang('Server Error'))
@section('description', lang("Sorry for the inconvenience, but we're working on it."))
