@extends('errors.layout')
@section('title', lang('Service Unavailable'))
@section('code', '503')
@section('message', lang('Service Unavailable'))
@section('description', lang('We will be back soon!'))
